# Generated by Django 4.1.2 on 2023-03-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_description', models.TextField()),
                ('image', models.CharField(max_length=250)),
                ('ordered_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
