# Generated by Django 4.1.2 on 2023-04-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproduct', '0002_rename_ordered_at_product_prepared_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(null=True, upload_to='static/uploads'),
        ),
    ]
