# Generated by Django 4.1.2 on 2023-05-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourproduct', '0006_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='barcoder/'),
        ),
    ]
