# Generated by Django 4.1.2 on 2023-05-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourproduct', '0010_alter_product_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
    ]
