# Generated by Django 4.1.2 on 2023-05-11 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipiecalculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='chief',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recipie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
